laporan tgl 01 desember 2022
muhdavi/laporan-practice-big-data pull request #142
Opened 2022-12-30 07:44 UTC by Muhammadikhsandev

laporan ini tentang hdfs-site.xml

2022-12-30 10:13 UTC, Muhammadikhsandev commented
berhasil menginstall hadoop

2022-12-31 07:46 UTC, muhdavi requested changes
dataWordCount.txt-nya kurang spasi setelah koma (,) sehingga semua dibaca satu baris data. tolong diperbaiki dulu ya.

2022-12-31 15:19 UTC, Muhammadikhsandev commented
dibagian mana pak?
yang kurang spasi setelah koma nya pak

2023-01-01 00:23 UTC, muhdavi commented
Coba lihat modul lagi cara penulisan dataWordCount.txt

2023-01-02 00:27 UTC, muhdavi approved these changes

2023-01-02 00:27 UTC, merged